BLOCK_SIZE = 25
SCREEN_WIDTH = 250 # 500
SCREEN_HEIGHT = 250 # 500

REWARD_LOSS = -1
REWARD_WIN = 1
REWARD_NULL = -0.1

SPEED = 10

MAX_WIDTH = SCREEN_WIDTH/BLOCK_SIZE
MAX_HEIGHT = SCREEN_HEIGHT/BLOCK_SIZE
MAX_SIZE = (SCREEN_HEIGHT/BLOCK_SIZE) * (SCREEN_WIDTH/BLOCK_SIZE)